CREATE TABLE IF NOT EXISTS `temza_titles` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `temza_title` varchar(255) NOT NULL,
  `play_id` int(11) DEFAULT NULL,
  `is_subscription` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_temza_title` (`temza_title`),
  KEY `idx_temza_titles_play_id` (`play_id`),
  CONSTRAINT `temza_titles_play_fk` FOREIGN KEY (`play_id`) REFERENCES `plays` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `temza_events` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `temza_title_id` int(11) DEFAULT NULL,
  `temza_title` varchar(255) NOT NULL,
  `preview_title` varchar(255) DEFAULT NULL,
  `preview_details` varchar(255) DEFAULT NULL,
  `date_label` varchar(100) DEFAULT NULL,
  `time_label` varchar(50) DEFAULT NULL,
  `month_label` char(7) NOT NULL,
  `event_date` date DEFAULT NULL,
  `start_time` time DEFAULT NULL,
  `hall` varchar(100) DEFAULT NULL,
  `chips_json` longtext,
  `cast_json` longtext,
  `responsibles_json` longtext,
  `department_tasks_json` longtext,
  `called_json` longtext,
  `notes_json` longtext,
  `raw_html` longtext,
  `raw_json` longtext,
  `scraped_at` datetime NOT NULL,
  `matched_event_id` int(11) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_temza_events_month` (`month_label`),
  KEY `idx_temza_events_date_time` (`event_date`,`start_time`),
  KEY `idx_temza_events_title` (`temza_title`),
  KEY `idx_temza_events_title_id` (`temza_title_id`),
  KEY `idx_temza_events_matched_event` (`matched_event_id`),
  CONSTRAINT `temza_events_title_fk` FOREIGN KEY (`temza_title_id`) REFERENCES `temza_titles` (`id`) ON DELETE SET NULL,
  CONSTRAINT `temza_events_events_raw_fk` FOREIGN KEY (`matched_event_id`) REFERENCES `events_raw` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
